//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimalShelter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AnimalShelter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;Name&quot;: &quot;Harry&quot;,
        ///    &quot;Age&quot;: &quot;10&quot;,
        ///    &quot;Gender&quot;: &quot;Male&quot;,
        ///    &quot;IsReserved&quot;: &quot;&quot;,
        ///    &quot;Price&quot;: 230.0,
        ///    &quot;Type&quot;: &quot;Cat&quot;,
        ///    &quot;BadHabit&quot;: &quot;Stinks&quot;
        ///  },
        ///  {
        ///    &quot;Name&quot;: &quot;Marlyn&quot;,
        ///    &quot;Age&quot;: &quot;5&quot;,
        ///    &quot;Gender&quot;: &quot;Female&quot;,
        ///    &quot;IsReserved&quot;: &quot;&quot;,
        ///    &quot;Price&quot;: 500.0,
        ///    &quot;Type&quot;: &quot;Dog&quot;,
        ///    &quot;LastWalkDay&quot;: &quot;2016-04-02T00:00:00&quot;
        ///  },
        ///  {
        ///    &quot;Name&quot;: &quot;Bernard&quot;,
        ///    &quot;Age&quot;: &quot;4&quot;,
        ///    &quot;Gender&quot;: &quot;Male&quot;,
        ///    &quot;IsReserved&quot;: &quot;&quot;,
        ///    &quot;Price&quot;: 270.0,
        ///    &quot;Type&quot;: &quot;Cat&quot;,
        ///    &quot;BadHabit&quot;: &quot;Blub&quot;
        ///  }
        ///] [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Animal {
            get {
                return ResourceManager.GetString("Animal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;Name&quot;: &quot;Blubs&quot;,
        ///    &quot;Price&quot;: 4.39
        ///  }
        ///]
        ///.
        /// </summary>
        internal static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
    }
}
